table aux_RFM_Recency
	isHidden
	excludeFromModelRefresh
	lineageTag: 6a620b6e-5d91-40cf-ac65-d3217d991370

	column id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 76351167-6aec-45ad-bfac-9ed9b96f3a88
		summarizeBy: sum
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Recencia
		dataType: string
		isHidden
		lineageTag: 56f2d2a8-1268-4c6c-b1f9-76107ccd0127
		summarizeBy: none
		sourceColumn: Recencia
		sortByColumn: id

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Min
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a7db7b5f-f06b-42b5-9492-4ab0c7249806
		summarizeBy: sum
		sourceColumn: Min

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Max
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c4446258-92c4-4a35-ab7e-74ca19cd1be5
		summarizeBy: sum
		sourceColumn: Max

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition aux_RFM_Recency-9f858d23-6064-4acc-9738-4c06ff5b7c2c = m
		mode: import
		queryGroup: 'Analise RFM'
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("LYqxEQAgCMR2obZ4QT3nsPXYfw0fsAgHCffK6dIk2eC0NcUbtfIIuuLH1BY/ZOG3tINHYKiUcnIPUMH9AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Recencia = _t, id = _t, Min = _t, Max = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Min", Int64.Type}, {"Max", Int64.Type}, {"id", Int64.Type}})
				in
				    #"Tipo Alterado"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

