table fLatest_update
	lineageTag: f9f45e75-8285-4618-864c-f479a8d5d1e4

	measure Latest_update = "Última atualização: "&MAX(fLatest_update[Última atualização]) - "03:00"
		lineageTag: 5e6034f6-e710-4549-96db-7f3a2070888a

	column 'Última atualização'
		dataType: dateTime
		formatString: General Date
		lineageTag: eb096217-777b-406c-b948-34619fff82ad
		summarizeBy: none
		sourceColumn: Última atualização

		annotation SummarizationSetBy = Automatic

	column Descrição
		dataType: string
		lineageTag: d8175df4-6943-444e-817e-765388a2392f
		summarizeBy: none
		sourceColumn: Descrição

		annotation SummarizationSetBy = Automatic

	partition fLatest_update-1358bde0-32ea-45ed-90b5-1d42f8f011e3 = m
		mode: import
		source =
				let
				    Fonte = #table({"Última atualização"},{{DateTime.LocalNow()}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Última atualização", type datetime, "pt-BR"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "Descrição", each "Última atualização", type text)
				in
				    #"Personalização Adicionada"

	annotation PBI_ResultType = Table

