table fLogins
	lineageTag: 9ba2b557-a5a7-4a3d-8f6d-e9aa24ec817a

	column login_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: dd02f4db-620d-4c41-be3a-0f932a2fcff4
		summarizeBy: none
		sourceColumn: login_date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column site_id
		dataType: int64
		formatString: 0
		lineageTag: fd77fd0c-6c91-4b7b-bf18-d52865762ac8
		summarizeBy: none
		sourceColumn: site_id

		annotation SummarizationSetBy = User

	column login_type
		dataType: string
		lineageTag: 7ac58ab6-a8db-493f-902f-b10463df8b88
		summarizeBy: none
		sourceColumn: login_type

		annotation SummarizationSetBy = Automatic

	column account_id
		dataType: int64
		formatString: 0
		lineageTag: 5058994b-af52-4b70-abe9-026125daef3b
		summarizeBy: none
		sourceColumn: account_id

		annotation SummarizationSetBy = Automatic

	column Vendedor? =
			
			IF(
			    LOOKUPVALUE(dVendedores[account_id],dVendedores[account_id],fLogins[account_id]) = BLANK(),
			    FALSE(),
			    TRUE()
			)
		lineageTag: 88bddc5e-df82-49f6-8b71-b1de6c05e120
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column account_user
		dataType: string
		lineageTag: 3a4e7171-c0d4-4b19-84c5-c14e4edcb3a0
		summarizeBy: none
		sourceColumn: account_user

		annotation SummarizationSetBy = Automatic

	column account_type
		dataType: string
		lineageTag: 164e8ab1-bf5e-46aa-b436-50093e3186a3
		summarizeBy: none
		sourceColumn: account_type

		annotation SummarizationSetBy = Automatic

	partition fLogins-e1311257-799d-4765-ab03-083d9886be61 = m
		mode: import
		queryGroup: Contas
		source =
				let
				    Fonte = PowerPlatform.Dataflows(null),
				    Workspaces = Fonte{[Id="Workspaces"]}[Data],
				    #"4ecf4510-897a-4317-b99c-52afa96130af" = Workspaces{[workspaceId="4ecf4510-897a-4317-b99c-52afa96130af"]}[Data],
				    #"b058979e-d5dd-4d00-87d4-7fd89d92e17f" = #"4ecf4510-897a-4317-b99c-52afa96130af"{[dataflowId="b058979e-d5dd-4d00-87d4-7fd89d92e17f"]}[Data],
				    fLogins_ = #"b058979e-d5dd-4d00-87d4-7fd89d92e17f"{[entity="fLogins",version=""]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(fLogins_, each [site_id] = 8638)
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

